# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('google_country', models.CharField(max_length=256)),
                ('google_info', models.CharField(max_length=512)),
                ('google_town', models.CharField(max_length=256)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('station_name', models.CharField(max_length=512)),
                ('uid', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
