# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0009_auto_20170831_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='aqi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='nh3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
