# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0011_auto_20170901_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
