# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0012_auto_20170904_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution', to='airpollution.Station'),
        ),
    ]
