# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0013_auto_20170906_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollution',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
