# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0014_pollution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollution',
            name='time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
